show tables;
CREATE TABLE QRCODE (
  IDX  INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  LOGIN_ID VARCHAR(30) NOT NULL UNIQUE,
  QRCODE VARCHAR(100) NOT NULL UNIQUE
);
drop table QRCODE;
select * from QRCODE;
delete from QRCODE;