show tables;
CREATE TABLE QRCODE (
  IDX  INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  LOGIN_ID VARCHAR(30) NOT NULL,
  CUSTOM_ID int(8) NOT NULL,
  CUSTOM_NM varchar(20) NOT NULL,
  QRCODE VARCHAR(100) NOT NULL UNIQUE
);
drop table QRCODE;
SELECT * FROM QRCODE ; 
delete from QRCODE;
